spring:
  profiles:
    active: dev
---
spring:
  profiles: dev

server:
  port: 9091

uaa:
  clientBase64Token: ZXJpY19jbGllbnQ6ZXJpY19zZWNyZXQ=
  uri: https://d7f73e42-13aa-4d3c-ac07-91adad9a93b5.predix-uaa.run.aws-usw02-pr.ice.predix.io

rabbitmq:
  tempQueueName: tempQueue
  uri: amqp://localhost
---
spring:
  profiles: cloud

uaa:
  clientId: ${CLIENT_ID}
  clientSecret: ${IM_SO_SECRET}
  clientBase64Token: ${CLIENT_BASE64_TOKEN}
  uri: ${UAA_URI}

rabbitmq:
  tempQueueName: tempQueue