spring:
  profiles:
    active: dev

---
spring:
  profiles: dev

uaa:
  clientId: predix_client
  clientSecret: IM_SO_SECRET
  clientBase64Token: cHJlZGl4X2NsaWVudDpJTV9TT19TRUNSRVQ=
  uri: https://d0919b4b-8e2b-4e07-bf22-2798603c6aad.predix-uaa.run.aws-usw02-pr.ice.predix.io

gatewayAPI:
  uri: http://localhost:9091

scheduler:
  time: 1000

asset:
  instanceId: af0fdf4e-0d14-4927-9570-550098455026
  uri: https://predix-asset.run.aws-usw02-pr.ice.predix.io

predix:
  oauth:
    grantType: client_credentials
    restHost: d0919b4b-8e2b-4e07-bf22-2798603c6aad.predix-uaa.run.aws-usw02-pr.ice.predix.io
    clientId: predix_client:IM_SO_SECRET
  websocket:
    pool:
      maxIdle: 5
      maxActive: 5
      maxWait: 8000
      maxInstances: 5
---
spring:
  profiles: cloud

uaa:
  clientId: ${CLIENT_ID}
  clientSecret: ${CLIENT_SECRET}
  clientBase64Token: ${CLIENT_BASE64_TOKEN}
  uri: ${UAA_URI}

gatewayAPI:
  uri: ${GATEWAY_URI}

scheduler:
  time: ${SCHEDULER_TIME}

predix:
  oauth:
    grantType: client_credentials
    restHost: ${REST_HOST}
    clientId: ${CLIENT_ID}
  websocket:
    pool:
      maxIdle: 5
      maxActive: 5
      maxWait: 8000
      maxInstances: 5